In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    print(i)

0
1
2
3
4


In [ ]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")


144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [3]:
import numpy as np

In [4]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totals:ndarray= student1 + student2
for total in totals:
    print(total)
    print("=========")

144
170
164
167
177


In [5]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32


In [8]:
np.random.randint(50,101,size=(50, 5))

array([[ 74,  66,  55,  86,  61],
       [ 93,  56,  69,  77,  59],
       [ 74,  65,  99,  77,  73],
       [ 79,  98,  68, 100,  70],
       [ 63,  63,  87,  55,  84],
       [ 59,  54,  83,  55,  75],
       [ 95,  70,  73,  54,  96],
       [ 96,  82,  77,  79,  58],
       [ 82,  88,  59,  54,  90],
       [ 82,  73,  88,  96,  61],
       [ 69,  62,  53,  72,  69],
       [ 76,  95,  63,  62,  55],
       [ 86,  56,  57,  58,  61],
       [ 60,  88,  51,  98,  51],
       [ 76,  65,  97,  74,  57],
       [ 99,  54,  51,  82,  74],
       [ 65,  85,  96,  87,  97],
       [ 59,  57,  83,  67,  96],
       [ 55,  92,  93,  80,  77],
       [ 95, 100,  95,  60,  86],
       [ 58,  80,  83,  56,  51],
       [ 91,  52,  90,  83,  52],
       [ 85,  98,  60,  89,  76],
       [ 53,  85,  56,  64,  55],
       [ 76,  51, 100,  56,  67],
       [ 89,  90,  99,  76,  58],
       [ 83,  54,  69,  61,  72],
       [ 58,  54,  58,  70,  90],
       [ 82,  78,  87, 100,  66],
       [ 73,  