In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    print(i)

0
1
2
3
4


In [2]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [4]:
import numpy as np

In [7]:
import numpy as np

student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])
type(student1)

numpy.ndarray

In [8]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totals:ndarray= student1 + student2
for total in totals:
    print(total)
    print("=========")

144
170
164
167
177


In [10]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [11]:
np.random.randint(50,101,size=(50, 5))


array([[ 74,  73,  63,  79,  57],
       [ 61,  88,  53,  98,  57],
       [ 51,  62,  79,  80,  84],
       [ 78,  89,  93,  87,  93],
       [ 98,  52,  95,  73,  51],
       [ 98,  98,  62,  70,  59],
       [ 95,  99,  54,  53,  76],
       [ 91,  96,  85,  62,  56],
       [ 64,  68,  89,  71,  77],
       [ 69,  80,  62,  93,  86],
       [ 77,  62,  62,  97,  54],
       [ 57,  76,  65,  61,  67],
       [ 83,  51,  62,  70,  82],
       [ 89,  69,  63,  55,  99],
       [ 52,  82,  75,  81,  73],
       [ 50,  56,  90,  50,  93],
       [ 99,  99,  84,  51,  70],
       [ 97,  58,  75,  98,  73],
       [ 78,  92,  97,  94,  65],
       [ 94,  67,  79,  60,  91],
       [ 73,  91,  97,  96,  63],
       [ 81,  98,  62,  89,  76],
       [ 62,  90,  82,  98,  94],
       [ 91,  51,  88,  65,  86],
       [ 93,  60,  59,  72,  94],
       [ 57,  84,  97,  54,  60],
       [ 58,  63,  50,  66,  74],
       [ 85,  56,  58,  63,  64],
       [ 72,  89,  64,  84,  59],
       [ 69,  