In [6]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [5]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2


[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [7]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [8]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [9]:
np.random.randint(50,101,size=(50, 5))

array([[ 86,  93,  74,  98,  59],
       [ 90,  90,  70,  71,  59],
       [ 75,  97,  76,  67,  87],
       [ 67,  83,  78,  85,  78],
       [ 90,  53,  66,  68,  84],
       [ 54,  63,  95,  59,  87],
       [ 89,  96,  73,  90,  59],
       [ 86,  94,  84,  94,  62],
       [ 85,  61,  75,  93,  96],
       [ 86,  91,  99,  79,  71],
       [ 93,  81,  81,  93, 100],
       [ 88,  98,  82,  74,  50],
       [ 94,  97, 100,  88,  55],
       [ 61,  74,  90, 100,  87],
       [ 55,  68,  82,  92,  70],
       [ 81,  91,  70,  58,  54],
       [ 54,  90,  98,  67,  85],
       [100,  91,  94,  76,  66],
       [ 81,  88,  55,  54,  87],
       [ 81,  77,  90,  63,  66],
       [ 80,  75,  80,  83,  91],
       [ 59,  73,  76,  53,  97],
       [ 71,  57,  94,  75,  93],
       [ 77,  61,  91,  54,  53],
       [ 60,  81,  56,  87,  88],
       [ 98,  83,  74,  81,  83],
       [ 57,  76,  91,  94,  73],
       [ 62,  89,  89,  68,  54],
       [ 65,  76,  68,  66,  94],
       [ 58,  