In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")


144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [4]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [5]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32


In [6]:
np.random.randint(50,101,size=(50, 5))

array([[ 97,  79,  90,  57,  93],
       [ 70,  63,  63,  60,  98],
       [ 89,  56,  96,  74,  65],
       [ 72,  56,  72,  54,  71],
       [ 67,  93,  94,  70,  86],
       [ 66, 100,  85,  77,  80],
       [100,  91,  65,  91,  92],
       [ 98,  53,  60,  96,  86],
       [ 62,  89,  70,  78,  58],
       [ 84,  56,  66,  78,  91],
       [ 59,  62,  51,  52,  61],
       [ 59,  87,  98,  90,  57],
       [ 92,  87,  69,  98,  57],
       [ 60,  87,  81,  51,  75],
       [ 97,  62,  80,  76,  51],
       [ 67,  72,  81,  55,  88],
       [ 93,  67,  80,  90,  85],
       [ 92,  50,  67,  68,  77],
       [ 87,  65,  93,  55,  85],
       [ 62,  82,  84,  84,  55],
       [ 99,  55,  83,  51,  62],
       [ 98,  73, 100,  57,  82],
       [ 97,  76,  65,  71,  94],
       [ 63,  70,  91,  87,  87],
       [ 51,  82,  61,  64,  81],
       [ 86,  55,  62,  96,  77],
       [ 66,  82,  94,  66,  77],
       [ 99,  77,  67,  64,  98],
       [ 85,  66,  54,  85,  80],
       [ 73,  