In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    print(i)

0
1
2
3
4


In [6]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2


[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [4]:
import numpy as np

In [5]:
import numpy as np

student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])
type(student1)

numpy.ndarray

In [6]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totals:ndarray= student1 + student2
for total in totals:
    print(total)
    print("=========")

144
170
164
167
177


In [8]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [11]:
np.random.randint(50,101,size=(50, 5))

array([[ 88,  70,  74,  71,  85],
       [ 90,  50,  71,  79,  50],
       [ 65,  98,  94,  94,  86],
       [ 81,  67,  98,  80,  97],
       [ 50,  51,  74,  62,  76],
       [ 52,  63,  91,  96,  86],
       [ 57,  81,  91,  87,  68],
       [ 68,  97,  65,  89,  76],
       [ 96,  61,  77,  70,  60],
       [ 69,  93,  99,  71,  89],
       [ 79,  65,  51,  72,  88],
       [ 70,  95,  68,  91,  85],
       [ 83,  72,  96,  92,  81],
       [ 92,  65,  61,  58,  66],
       [ 67,  57,  65,  98,  85],
       [ 98,  73,  93,  86,  97],
       [ 97,  71,  71,  90, 100],
       [ 87,  91,  69,  70,  53],
       [ 86,  71,  84,  53,  60],
       [ 76,  72,  74,  63,  52],
       [ 57,  55,  73,  79,  91],
       [ 82,  53,  78,  59,  65],
       [ 62,  81,  67,  83,  80],
       [ 62,  99,  69,  97,  77],
       [ 99,  87,  94,  99,  72],
       [ 77,  73,  70,  93,  90],
       [ 50,  84,  69,  69,  67],
       [ 97, 100,  66,  84,  60],
       [ 87,  77,  52,  98,  78],
       [ 70,  