In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    print(i)

0
1
2
3
4


In [ ]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")


144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [2]:
import numpy as np

In [3]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totals:ndarray= student1 + student2
for total in totals:
    print(total)
    print("=========")

144
170
164
167
177


In [4]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32


In [6]:
np.random.randint(50,101,size=(50, 5))

array([[ 54,  97,  89,  96,  94],
       [ 75,  97,  63,  72,  67],
       [ 91,  50,  68,  76,  74],
       [ 57,  52,  63,  75,  85],
       [ 86,  68,  91,  82, 100],
       [ 95,  63,  67,  77,  63],
       [ 91,  85,  74,  74,  86],
       [ 78,  99,  76,  69,  77],
       [ 72,  98,  78,  81,  89],
       [ 86,  72,  56,  90,  71],
       [ 86,  64,  79,  85,  64],
       [ 78,  83,  53,  86,  86],
       [ 56,  96,  96,  92,  50],
       [ 90,  63,  55,  85,  67],
       [ 81, 100,  79,  86,  86],
       [ 50,  72,  93,  80,  74],
       [ 73,  57,  72,  81,  92],
       [ 58,  88,  70,  54,  86],
       [ 63,  62,  50,  53,  68],
       [ 98,  59,  91,  99,  75],
       [ 85,  57,  51,  81,  73],
       [ 77,  60,  56,  99,  81],
       [100,  52,  54,  68,  84],
       [ 98,  90,  78,  50,  62],
       [ 81,  77,  95,  53,  76],
       [ 80,  71,  81,  59,  59],
       [ 99,  50,  56,  79,  85],
       [ 95,  96,  66,  90,  70],
       [ 76,  94,  71,  53,  60],
       [ 72,  